import { Poppins } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import { UserProvider } from "./context/UserContext";

const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ["400", "500", "700"]
});

export const metadata = {
  title: "Pet App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className} style={{backgroundColor: "#fafafa"}}>
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}